image:
    name: hashicorp/terraform:light
    entrypoint:
        - '/usr/bin/env'

before_script:
    - rm -rf .terraform
    - terraform --version
    - terraform init

stages:
    - validate
    - plan
    - apply
    - destroy

validate: 
    stage: validate
    script:
        - terraform validate

plan:
    stage: plan
    script:
        - terraform plan
    dependencies:
        - "validate"

apply:
    stage: apply
    script:
        - terraform plan
        - terraform apply --auto-approve
    dependencies:
        - "plan"
    when: manual

destroy:
    stage: destroy
    script:
        - terraform destroy --auto-approve
    dependencies:
        - "apply"
    when: manual
